CREATE TABLE patients (
  id SERIAL PRIMARY KEY,
  name varchar,
  date_of_birth date
);

CREATE TABLE medical_histories (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admitted_at timestamp,
  patient_id INT REFERENCES patients(id),
  status varchar(50)
);

CREATE TABLE treatments (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type varchar(50),
  name varchar(100)
);

CREATE TABLE invoices (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  total_amount decimal,
  generated_at timestamp,
  payed_at timestamp,
  medical_history_id INT REFERENCES medical_histories(id)
);

CREATE TABLE invoice_items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_price decimal,
  quantity INT,
  total_price decimal,
  invoice_id INT REFERENCES invoices(id),
  treatment_id INT REFERENCES treatments(id)
);

-- JOINING TABLE FOR medical_histories and treatments
CREATE TABLE medical_histories_treaments (
  medical_history_id INT REFERENCES medical_histories(id),
  treatment_id INT REFERENCES treatments(id)
);
--FK indexes
CREATE INDEX patient_id_index ON medical_histories(patient_id ASC);
CREATE INDEX medical_history_id_index ON invoices(medical_history_id ASC);
CREATE INDEX invoice_id_index ON invoice_items(invoice_id ASC);
CREATE INDEX treatment_id_index ON invoice_items(treatment_id ASC);
CREATE INDEX medical_histories_id_index ON medical_histories_treaments(medical_history_id ASC);
CREATE INDEX treaments_id_index ON medical_histories_treaments(treatment_id ASC);
